version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    container_name: php-web
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: kampus_db
      MYSQL_USER: userphp
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    container_name: mysql-db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
